# Support Vector Machine - SVM

## Classification and Regression

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [22]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
iris = fetch_ucirepo(id=53) 
  
# data (as pandas dataframes) 
X = iris.data.features 
y = iris.data.targets 
  
# metadata 
print(iris.metadata) 
  
# variable information 
print(iris.variables) 

{'uci_id': 53, 'name': 'Iris', 'repository_url': 'https://archive.ics.uci.edu/dataset/53/iris', 'data_url': 'https://archive.ics.uci.edu/static/public/53/data.csv', 'abstract': 'A small classic dataset from Fisher, 1936. One of the earliest known datasets used for evaluating classification methods.\n', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 150, 'num_features': 4, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1936, 'last_updated': 'Tue Sep 12 2023', 'dataset_doi': '10.24432/C56C76', 'creators': ['R. A. Fisher'], 'intro_paper': {'title': 'The Iris data set: In search of the source of virginica', 'authors': 'A. Unwin, K. Kleinman', 'published_in': 'Significance, 2021', 'year': 2021, 'url': 'https://www.semanticscholar.org/paper/4599862ea877863669a6a8e63a3c707a787d5d7e', 'doi': '1740-9713.01589'}, 'add

In [20]:
ls

 El volumen de la unidad C es Windows-SSD
 El número de serie del volumen es: 9E6A-3162

 Directorio de C:\Users\carlo\Documents\Machine-Learning\SupportVectorMachine

14/08/2024  12:08 a. m.    <DIR>          .
14/08/2024  12:05 a. m.    <DIR>          ..
14/08/2024  12:05 a. m.    <DIR>          .ipynb_checkpoints
14/08/2024  12:08 a. m.             1,233 VectorMachine.ipynb
               1 archivos          1,233 bytes
               3 dirs  591,224,406,016 bytes libres


In [26]:
X

sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [28]:
y

class
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

In [30]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [34]:
from sklearn.svm import SVC

In [36]:
model = SVC(gamma = 'auto')

In [42]:
model.fit(X_train, y_train)

C:\Users\carlo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(gamma='auto')

In [44]:
predictions = model.predict(X_test)

In [46]:
predictions

array(['Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa'], dtype=object)

In [48]:
y_test

class
21       Iris-setosa
104   Iris-virginica
87   Iris-versicolor
148   Iris-virginica
121   Iris-virginica
100   Iris-virginica
58   Iris-versicolor
44       Iris-setosa
95   Iris-versicolor
28       Iris-setosa
47       Iris-setosa
108   Iris-virginica
125   Iris-virginica
51   Iris-versicolor
107   Iris-virginica
66   Iris-versicolor
61   Iris-versicolor
62   Iris-versicolor
89   Iris-versicolor
34       Iris-setosa
41       Iris-setosa
86   Iris-versicolor
134   Iris-virginica
93   Iris-versicolor
136   Iris-virginica
69   Iris-versicolor
52   Iris-versicolor
45       Iris-setosa
146   Iris-virginica
68   Iris-versicolor
94   Iris-versicolor
19       Iris-setosa
60   Iris-versicolor
10       Iris-setosa
59   Iris-versicolor
35       Iris-setosa
3        Iris-setosa
115   Iris-virginica
138   Iris-virginica
73   Iris-versicolor
7        Iris-setosa
6        Iris-setosa
50   Iris-versicolor
144   Iris-virginica
38       Iris-setosa

In [50]:
from sklearn.metrics import classification_report, confusion_matrix

In [52]:
print(classification_report(y_test, predictions))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        14
Iris-versicolor       0.95      1.00      0.97        18
 Iris-virginica       1.00      0.92      0.96        13

       accuracy                           0.98        45
      macro avg       0.98      0.97      0.98        45
   weighted avg       0.98      0.98      0.98        45



In [54]:
print(confusion_matrix(y_test, predictions))

[[14  0  0]
 [ 0 18  0]
 [ 0  1 12]]
