# Numpy Arrays

In [2]:
import numpy as np

In [5]:
l = [1, 2, 3, 4]
array = np.array(l)
array

array([1, 2, 3, 4])

In [6]:
l2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array2 = np.array(l2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## arange, zeros, ones, linspace, eye

In [7]:
array = np.arange(5)
array

array([0, 1, 2, 3, 4])

In [8]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
np.linspace(5, 8, 30)

array([5.        , 5.10344828, 5.20689655, 5.31034483, 5.4137931 ,
       5.51724138, 5.62068966, 5.72413793, 5.82758621, 5.93103448,
       6.03448276, 6.13793103, 6.24137931, 6.34482759, 6.44827586,
       6.55172414, 6.65517241, 6.75862069, 6.86206897, 6.96551724,
       7.06896552, 7.17241379, 7.27586207, 7.37931034, 7.48275862,
       7.5862069 , 7.68965517, 7.79310345, 7.89655172, 8.        ])

In [19]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random numbers - rand & randn & randint

In [20]:
np.random.rand(5)

array([0.78704351, 0.60765879, 0.56127956, 0.22802333, 0.27758548])

In [21]:
np.random.rand(3, 4)

array([[0.47754208, 0.86886179, 0.36099709, 0.36234092],
       [0.77975947, 0.33479053, 0.25854315, 0.9684027 ],
       [0.71733696, 0.63194979, 0.81952054, 0.72818762]])

In [22]:
np.random.randn(4)

array([ 0.82560402, -0.30633169, -1.35151091,  1.04829776])

In [24]:
np.random.randn(3, 5)

array([[-1.39219078,  2.6571729 ,  0.08218439, -0.73578882,  1.20928377],
       [ 0.18397387,  1.70715984,  1.32657046,  1.85544105, -0.87820729],
       [ 1.89979313,  0.46632191,  0.02730942,  0.89809239, -0.57435782]])

In [25]:
np.random.randint(5)

2