# Numpy Arrays

In [1]:
import numpy as np

In [5]:
l = [1, 2, 3, 4]
array = np.array(l)
array

array([1, 2, 3, 4])

In [6]:
l2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array2 = np.array(l2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## arange, zeros, ones, linspace, eye

In [7]:
array = np.arange(5)
array

array([0, 1, 2, 3, 4])

In [8]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
np.linspace(5, 8, 30)

array([5.        , 5.10344828, 5.20689655, 5.31034483, 5.4137931 ,
       5.51724138, 5.62068966, 5.72413793, 5.82758621, 5.93103448,
       6.03448276, 6.13793103, 6.24137931, 6.34482759, 6.44827586,
       6.55172414, 6.65517241, 6.75862069, 6.86206897, 6.96551724,
       7.06896552, 7.17241379, 7.27586207, 7.37931034, 7.48275862,
       7.5862069 , 7.68965517, 7.79310345, 7.89655172, 8.        ])

In [19]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random numbers - rand & randn & randint

In [20]:
np.random.rand(5)

array([0.78704351, 0.60765879, 0.56127956, 0.22802333, 0.27758548])

In [21]:
np.random.rand(3, 4)

array([[0.47754208, 0.86886179, 0.36099709, 0.36234092],
       [0.77975947, 0.33479053, 0.25854315, 0.9684027 ],
       [0.71733696, 0.63194979, 0.81952054, 0.72818762]])

In [22]:
np.random.randn(4)

array([ 0.82560402, -0.30633169, -1.35151091,  1.04829776])

In [24]:
np.random.randn(3, 5)

array([[-1.39219078,  2.6571729 ,  0.08218439, -0.73578882,  1.20928377],
       [ 0.18397387,  1.70715984,  1.32657046,  1.85544105, -0.87820729],
       [ 1.89979313,  0.46632191,  0.02730942,  0.89809239, -0.57435782]])

In [33]:
np.random.randint(5, 20)

14

In [34]:
np.random.randint(1, 20, 10)

array([ 4,  7, 17, 12,  5, 11,  8, 14, 19,  2])

## reshape

In [36]:
arr = np.random.randint(1, 100, 25)
arr

array([ 9, 21, 39, 51, 62, 36, 93, 54, 95, 45, 61, 15, 82, 39, 24, 40, 94,
       94, 42, 66, 51, 68, 97, 28, 48])

In [38]:
matrix = arr.reshape(5, 5)
matrix

array([[ 9, 21, 39, 51, 62],
       [36, 93, 54, 95, 45],
       [61, 15, 82, 39, 24],
       [40, 94, 94, 42, 66],
       [51, 68, 97, 28, 48]])

## max & min

In [43]:
ar = np.random.randint(1, 100, 50)
ar

array([ 3,  3, 33, 27, 73, 15, 98, 80, 96, 65, 77, 95, 44, 44, 66, 36, 74,
       11, 75, 20, 95, 17, 72, 11, 85, 27, 56, 15, 67,  3, 80, 27, 51, 23,
       42, 93, 32, 70, 67, 55, 11, 60, 97, 38,  3, 53, 25, 13, 86, 54])

In [49]:
max_value = ar.max()
position_max = ar.argmax()
max_value

98

In [50]:
position_max

6

In [51]:
min_value = ar.min()
position_min = ar.argmin()
min_value

3

In [53]:
position_min

0

## indexing

In [55]:
a = np.arange(0, 10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
a[0]

0

In [57]:
a[-1]

9

In [58]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
a[6:]

array([6, 7, 8, 9])

In [60]:
a[:5]

array([0, 1, 2, 3, 4])

In [61]:
a2 = a.copy()
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a2[0] = 1000
a2

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [64]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
m[0]

array([1, 2, 3])

In [67]:
m[:1]

array([[1, 2, 3]])

## select elements by condition

In [4]:
arra = np.arange(1,14)
arra

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [5]:
condition = arra > 5

In [6]:
condition

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True])

In [8]:
arra[condition]

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [9]:
arra6 = arra[condition]
arra6

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [12]:
arra[arra > 6]

array([ 7,  8,  9, 10, 11, 12, 13])

In [13]:
arra[arra % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

## array operations

In [14]:
array = np.arange(0, 10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
array * 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [18]:
array - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [19]:
array + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
array2 = np.arange(5, 15)
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
array2 - array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [22]:
array * array2

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [23]:
np.sqrt(array2)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [24]:
np.max(array)

9

In [25]:
np.min(array)

0

# Execises

## Exercise 1
Create a list of sequential numbers with the minimum value of 10 and the maximum value of 39. Convert this list into a 2-dimensional list or array (3 rows and 10 columns). Displays the value of the element in the upper right corner of the matrix.

In [3]:
lista = np.arange(10, 40)
lista

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [5]:
lista = lista.reshape(3, 10)
lista

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
lista[0,-1]